services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo:alpine
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  bot:
    build:
      context: .
    container_name: bot
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data: